### ISSUE TITLE
Пропозиції що до покращення

### ISSUE THREAD

**Issue by alexvoz** [olexandr17/PhaserSpriteSheetUnpacker#1]
- зробити 3й параметр не обов'язковим. назву теки зробити як і назву файла json.
- зробити 2й параметр не обов'язковим. назву png файла брати с вузла meta, параметр image в поточному каталогу (або каталогу json-файла)
- додати обробку обертання фреймів

**Comment by olexandr17** [comment]
1 and 2 are done
For item #3 please create new issue and hope I will have free time in future ;)

**Comment by alexvoz** [comment]
Its Awesome!
